#!/usr/bin/env bash
# Pick free ports and write env files for custom-web-ui local dev + Playwright.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
HOST="${CUSTOM_WEB_UI_HOST:-127.0.0.1}"
FE_START="${PREFERRED_FRONTEND_PORT:-3000}"
BE_START="${PREFERRED_BACKEND_PORT:-8000}"

PORTS_ENV="${CUSTOM_WEB_UI_PORTS_ENV:-$ROOT/.ports.env}"
ENV_LOCAL="${CUSTOM_WEB_UI_ENV_LOCAL:-$ROOT/frontend/.env.local}"

{
  echo "# Generated by scripts/apply-local-ports.sh — safe to regenerate"
  echo "# Usage: source \"$PORTS_ENV\""
  python3 "$ROOT/scripts/pick_ports.py" \
    --host "$HOST" \
    --frontend-start "$FE_START" \
    --backend-start "$BE_START"
} > "$PORTS_ENV"

set -a
# shellcheck disable=SC1091
source "$PORTS_ENV"
set +a

{
  echo "# Generated by scripts/apply-local-ports.sh — safe to regenerate"
  echo "# Next.js: API rewrites + middleware session check"
  echo "API_PROXY_TARGET=$API_PROXY_TARGET"
  echo "INTERNAL_API_URL=$INTERNAL_API_URL"
} > "$ENV_LOCAL"

echo "Wrote: $ENV_LOCAL"
echo "Wrote: $PORTS_ENV"
echo ""
echo "Ports: frontend=$CUSTOM_WEB_UI_FRONTEND_PORT backend=$CUSTOM_WEB_UI_BACKEND_PORT"
echo ""
echo "Backend (set PYTHONPATH / KH_APP_DATA_DIR per custom-web-ui/README.md), example:"
echo "  uvicorn app.main:app --host $HOST --port $CUSTOM_WEB_UI_BACKEND_PORT"
echo ""
echo "Frontend:"
echo "  cd frontend && npm run dev -- --hostname $HOST --port $CUSTOM_WEB_UI_FRONTEND_PORT"
echo ""
echo "Playwright E2E:"
echo "  source \"$PORTS_ENV\" && cd frontend && PLAYWRIGHT_SKIP_WEBSERVER=1 npm run test:e2e"
